// eslint-disable-next-line import/prefer-default-export
export const ALLOWED_FIRST_KEYS = [
  'CommandOrControl',
  'Command',
  'Control',
  'Alt',
  'Option',
  'AltGr',
  'Shift',
  'Super',
  'Meta',
  'Plus',
  'Space',
  'Tab',
  'Capslock',
  'Numlock',
  'Scrollock',
  'Backspace',
  'Delete',
  'Insert',
  'PageUp',
  'PageDown',
  'Escape',
];
